// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-OdPk44hTWYo7RGhbBOY58qlhOyT7Yo',
    appId: '1:323446587654:android:973d437e0b8ccd06861e87',
    messagingSenderId: '323446587654',
    projectId: 'asaxiybooks-4e1aa',
    storageBucket: 'asaxiybooks-4e1aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqzwcL6xtJYUUlyhhpHyqR3aAPSmcKIQ',
    appId: '1:323446587654:ios:38579fd35bac3625861e87',
    messagingSenderId: '323446587654',
    projectId: 'asaxiybooks-4e1aa',
    storageBucket: 'asaxiybooks-4e1aa.appspot.com',
    iosClientId: '323446587654-fu5k357d0365il4psc09teluqdjua0na.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactAppFirebaseBloc',
  );

}